/*
# [Function Security Hardening]
[Sets a secure search_path for database functions to mitigate potential security risks.]

## Query Description: [This operation modifies existing database functions to explicitly set the `search_path`. This prevents hijacking attacks by ensuring functions do not accidentally execute malicious code from untrusted schemas. It's a standard security best practice.]

## Metadata:
- Schema-Category: ["Safe", "Security"]
- Impact-Level: ["Low"]
- Requires-Backup: [false]
- Reversible: [true]

## Structure Details:
- Modifies functions: `update_user_level`, `update_total_completed_chapters`, `create_user_profile`

## Security Implications:
- RLS Status: [Not Applicable]
- Policy Changes: [No]
- Auth Requirements: [Superuser]

## Performance Impact:
- Indexes: [Not Applicable]
- Triggers: [Not Applicable]
- Estimated Impact: [None]
*/
ALTER FUNCTION public.create_user_profile() SET search_path = public;
ALTER FUNCTION public.update_total_completed_chapters() SET search_path = public;
ALTER FUNCTION public.update_user_level() SET search_path = public;


/*
# [Create Monthly Gifts Table]
[Creates the `monthly_gifts` table to store information about the 12 monthly bonus ebooks.]

## Query Description: [This operation creates a new table named `monthly_gifts` to store details about monthly ebooks. It is a non-destructive operation and does not affect any existing data.]

## Metadata:
- Schema-Category: ["Structural"]
- Impact-Level: ["Low"]
- Requires-Backup: [false]
- Reversible: [true]

## Structure Details:
- Table: `monthly_gifts`
- Columns: `id`, `month`, `title`, `description`, `cover_image_url`, `pdf_url`, `content`, `created_at`

## Security Implications:
- RLS Status: [Enabled]
- Policy Changes: [Yes, policies will be added]
- Auth Requirements: [Authenticated users]

## Performance Impact:
- Indexes: [Primary key on `id`, unique index on `month`]
- Triggers: [No]
- Estimated Impact: [Low]
*/
CREATE TABLE IF NOT EXISTS public.monthly_gifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month INT NOT NULL UNIQUE CHECK (month >= 1 AND month <= 12),
    title TEXT NOT NULL,
    description TEXT,
    cover_image_url TEXT,
    pdf_url TEXT,
    content JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);


/*
# [Enable RLS for Monthly Gifts]
[Enables Row Level Security on the `monthly_gifts` table and adds a policy to allow authenticated users to read the data.]

## Query Description: [This operation secures the `monthly_gifts` table by enabling RLS. It adds a policy that allows any logged-in user to view the monthly gifts. This is a safe and necessary security measure.]

## Metadata:
- Schema-Category: ["Security"]
- Impact-Level: ["Low"]
- Requires-Backup: [false]
- Reversible: [true]

## Structure Details:
- Table: `monthly_gifts`

## Security Implications:
- RLS Status: [Enabled]
- Policy Changes: [Yes, new SELECT policy added]
- Auth Requirements: [Authenticated users]

## Performance Impact:
- Indexes: [No]
- Triggers: [No]
- Estimated Impact: [Low, may add a slight overhead to queries, which is expected for RLS.]
*/
ALTER TABLE public.monthly_gifts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated users to read monthly gifts" ON public.monthly_gifts;
CREATE POLICY "Allow authenticated users to read monthly gifts"
ON public.monthly_gifts
FOR SELECT
TO authenticated
USING (true);


/*
# [Populate Monthly Gifts Data]
[Inserts the data for the 12 monthly bonus ebooks into the `monthly_gifts` table.]

## Query Description: [This operation populates the `monthly_gifts` table with initial data for each month of the year. It is a data insertion operation and is safe to run. It does not modify or delete any existing data.]

## Metadata:
- Schema-Category: ["Data"]
- Impact-Level: ["Low"]
- Requires-Backup: [false]
- Reversible: [true]

## Structure Details:
- Table: `monthly_gifts`

## Security Implications:
- RLS Status: [Not Applicable to the INSERT itself]
- Policy Changes: [No]
- Auth Requirements: [Superuser]

## Performance Impact:
- Indexes: [No]
- Triggers: [No]
- Estimated Impact: [Low]
*/
INSERT INTO public.monthly_gifts (month, title, description, cover_image_url, pdf_url, content) VALUES
(1, 'Ebook de Janeiro: Renovação', 'Comece o ano com intenções claras e práticas de renovação energética.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/a78bfa/ffffff?text=Janeiro', '/pdfs/janeiro.pdf', '{}'),
(2, 'Ebook de Fevereiro: Amor Próprio', 'Aprofunde a relação consigo mesmo(a) através do amor e aceitação.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/f472b6/ffffff?text=Fevereiro', '/pdfs/fevereiro.pdf', '{}'),
(3, 'Ebook de Março: Equilíbrio', 'Encontre o equilíbrio entre suas energias masculina e feminina.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/60a5fa/ffffff?text=Março', '/pdfs/marco.pdf', '{}'),
(4, 'Ebook de Abril: Florescer', 'Práticas para florescer sua criatividade e expressão pessoal.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/34d399/ffffff?text=Abril', '/pdfs/abril.pdf', '{}'),
(5, 'Ebook de Maio: Nutrição da Alma', 'Alimente sua alma com práticas de gratidão e contentamento.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/fbbf24/ffffff?text=Maio', '/pdfs/maio.pdf', '{}'),
(6, 'Ebook de Junho: Conexão Solar', 'Celebre a luz interior e a energia do solstício.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/f97316/ffffff?text=Junho', '/pdfs/junho.pdf', '{}'),
(7, 'Ebook de Julho: Introspecção', 'Um guia para o mergulho interior e a autoanálise.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/8b5cf6/ffffff?text=Julho', '/pdfs/julho.pdf', '{}'),
(8, 'Ebook de Agosto: Força Interior', 'Desperte sua força e coragem para superar desafios.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/ef4444/ffffff?text=Agosto', '/pdfs/agosto.pdf', '{}'),
(9, 'Ebook de Setembro: Colheita', 'Reconheça e celebre suas conquistas e aprendizados.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/84cc16/ffffff?text=Setembro', '/pdfs/setembro.pdf', '{}'),
(10, 'Ebook de Outubro: Transformação', 'Práticas para liberar o que não serve mais e se transformar.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/a855f7/ffffff?text=Outubro', '/pdfs/outubro.pdf', '{}'),
(11, 'Ebook de Novembro: Gratidão', 'Aprofunde sua prática de gratidão e aprecie o momento presente.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/14b8a6/ffffff?text=Novembro', '/pdfs/novembro.pdf', '{}'),
(12, 'Ebook de Dezembro: Celebração', 'Celebre o ciclo que se fecha e prepare-se para um novo começo.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/ec4899/ffffff?text=Dezembro', '/pdfs/dezembro.pdf', '{}')
ON CONFLICT (month) DO NOTHING;
