/*
          # [Operation Name]
          Create Monthly Gifts Table and Data

          ## Query Description: [This operation creates a new table `monthly_gifts` to store the 12 monthly ebook gifts. It also inserts the data for all 12 months with placeholder content. This is a non-destructive operation and is safe to run on the existing database.]
          
          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "Low"
          - Requires-Backup: false
          - Reversible: true
          
          ## Structure Details:
          - Creates table: `public.monthly_gifts`
          - Columns: `id`, `month_number`, `title`, `description`, `cover_image_url`, `pdf_url`, `created_at`
          
          ## Security Implications:
          - RLS Status: Enabled
          - Policy Changes: Yes
          - Auth Requirements: Creates a new policy to allow authenticated users to read from the table.
          
          ## Performance Impact:
          - Indexes: Adds a primary key on `id` and an index on `month_number`.
          - Triggers: None
          - Estimated Impact: Low. The table is small and queries will be efficient.
          */

-- 1. Create the table for monthly gifts
CREATE TABLE public.monthly_gifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_number INT NOT NULL CHECK (month_number >= 1 AND month_number <= 12),
    title TEXT NOT NULL,
    description TEXT,
    cover_image_url TEXT,
    pdf_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add comments to the table and columns
COMMENT ON TABLE public.monthly_gifts IS 'Stores the 12 monthly gifts (ebooks) for users.';
COMMENT ON COLUMN public.monthly_gifts.month_number IS 'The month of the year (1=Jan, 12=Dec) when the gift is unlocked.';

-- 3. Create an index for faster lookups by month
CREATE INDEX idx_monthly_gifts_month_number ON public.monthly_gifts(month_number);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.monthly_gifts ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS policies
-- Allow authenticated users to read all gifts
CREATE POLICY "Allow authenticated users to read all gifts"
ON public.monthly_gifts
FOR SELECT
TO authenticated
USING (true);

-- 6. Insert the 12 monthly gifts (placeholder data)
INSERT INTO public.monthly_gifts (month_number, title, description, cover_image_url, pdf_url)
VALUES
(1, 'Ebook de Janeiro: O Poder da Intenção', 'Comece o ano definindo intenções poderosas para sua jornada de autoconhecimento.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/6366F1/FFFFFF?text=Janeiro', '/ebooks/janeiro.pdf'),
(2, 'Ebook de Fevereiro: Amor Próprio Radical', 'Um guia para cultivar um relacionamento profundo e amoroso consigo mesmo.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/8B5CF6/FFFFFF?text=Fevereiro', '/ebooks/fevereiro.pdf'),
(3, 'Ebook de Março: A Arte da Presença', 'Técnicas de mindfulness para viver o momento presente com mais intensidade.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/A855F7/FFFFFF?text=Março', '/ebooks/marco.pdf'),
(4, 'Ebook de Abril: Despertar da Energia', 'Exercícios práticos para sentir e direcionar sua energia vital (prana).', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/D946EF/FFFFFF?text=Abril', '/ebooks/abril.pdf'),
(5, 'Ebook de Maio: Florescer da Sensualidade', 'Reconecte-se com sua sensualidade de forma sagrada e consciente.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/EC4899/FFFFFF?text=Maio', '/ebooks/maio.pdf'),
(6, 'Ebook de Junho: Solstício da Alma', 'Rituais e práticas para celebrar o pico de energia e luz interior.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/F472B6/FFFFFF?text=Junho', '/ebooks/junho.pdf'),
(7, 'Ebook de Julho: Mergulho nas Emoções', 'Aprenda a navegar e transformar suas emoções com a sabedoria tântrica.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/EF4444/FFFFFF?text=Julho', '/ebooks/julho.pdf'),
(8, 'Ebook de Agosto: A Força do Leão Interior', 'Desperte sua coragem, poder pessoal e autenticidade.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/F97316/FFFFFF?text=Agosto', '/ebooks/agosto.pdf'),
(9, 'Ebook de Setembro: Equilíbrio e Harmonia', 'Práticas para equilibrar as energias masculina e feminina dentro de você.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/F59E0B/FFFFFF?text=Setembro', '/ebooks/setembro.pdf'),
(10, 'Ebook de Outubro: Colheita e Gratidão', 'Um diário de gratidão guiado para reconhecer as bênçãos da sua jornada.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/EAB308/FFFFFF?text=Outubro', '/ebooks/outubro.pdf'),
(11, 'Ebook de Novembro: A Sombra como Aliada', 'Integre seus aspectos sombrios e descubra a força que eles escondem.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/84CC16/FFFFFF?text=Novembro', '/ebooks/novembro.pdf'),
(12, 'Ebook de Dezembro: Celebração do Ser', 'Um guia para fechar o ano celebrando sua evolução e se preparando para um novo ciclo.', 'https://img-wrapper.vercel.app/image?url=https://placehold.co/400x600/22C55E/FFFFFF?text=Dezembro', '/ebooks/dezembro.pdf');
